openapi: 3.1.0
info:
  title: Google Drive API
  description: API for interacting with Google Drive
  version: "1.0.0"

servers:
  - url: https://www.googleapis.com/drive/v3

paths:
  /files:
    get:
      operationId: ListFiles
      summary: List files
      description: Retrieve a list of files in the user's Google Drive.
      parameters:
        - name: q
          in: query
          description: Query string for searching files.
          required: false
          schema:
            type: string
        - name: includeItemsFromAllDrives
          in: query
          description: Whether both My Drive and shared drive items should be included in results.
          required: false
          schema:
            type: string
        - name: supportsAllDrives
          in: query
          description: Whether the requesting application supports both My Drives and shared drives.
          required: false
          schema:
            type: string
        - name: pageSize
          in: query
          description: Maximum number of files to return.
          required: false
          schema:
            type: integer
            default: 10
        - name: pageToken
          in: query
          description: Token for continuing a previous list request.
          required: false
          schema:
            type: string
        - name: fields
          in: query
          description: Comma-separated list of fields to include in the response.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: A list of files.
          content:
            application/json:
              schema:
                type: object
                properties:
                  kind:
                    type: string
                    example: drive#fileList
                  nextPageToken:
                    type: string
                    description: Token to retrieve the next page of results.
                  files:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        mimeType:
                          type: string

  /files/{fileId}:
    get:
      operationId: getMetadata
      summary: Get file metadata
      description: Retrieve metadata for a specific file.
      parameters:
        - name: fileId
          in: path
          description: ID of the file to retrieve.
          required: true
          schema:
            type: string
        - name: fields
          in: query
          description: Comma-separated list of fields to include in the response.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Metadata of the file.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  mimeType:
                    type: string
                  description:
                    type: string
                  createdTime:
                    type: string
                    format: date-time

  /files/{fileId}/export:
    get:
      operationId: export
      summary: Export a file
      description: Export
