openapi: 3.1.0
info:
  title: OpenAI Relay API
  version: "1.0.0"
  description: BIFL-grade relay with essential OpenAI endpoints
servers:
  - url: https://chatgpt-team-relay.onrender.com

paths:
  /v1/chat/completions:
    post:
      operationId: chatCompletions_create
      summary: Create chat completion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [model, messages]
              properties:
                model: { type: string }
                messages:
                  type: array
                  items: 
                    type: object
                    required: [role, content]
                    properties:
                      role: { type: string, enum: [user, assistant, system, tool] }
                      content: { type: string }
                stream: { type: boolean, default: false }
      responses:
        '200': { description:: Chat completion created }
  //v1/embeddings:
    post:
      operationId: embeddings_create
      summary: Create embedding
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [model, input]
              properties:
                model: { type: string }
                input: { type: string }
      responses:
        '200': { description: Embedding created }
  ... # content truncated to fit within GIT limk