openapi: 3.1.0
info:
  title: ChatGPT Team Relay (BIFL Surface)
  version: '2025-10-24'
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: |
    OpenAI-compatible relay exposing unified /v1/responses plus non-UI-native surfaces:
    Files/Uploads, Images, Audio, Vector Stores, and Videos (Sora 2 Pro).
    Legacy/sunset routes excluded. Exactly 30 operations.
servers:
  - url: https://chatgpt-team-relay.onrender.com
security:
  - BearerAuth: []
tags:
  - name: Responses
    description: Unified response creation and control
  - name: Models
    description: Retrieve available models
  - name: Files
    description: File upload and retrieval
  - name: Uploads
    description: Multipart upload management
  - name: Images
    description: Image generation and editing
  - name: Audio
    description: Audio transcription, translation, and speech
  - name: Vector Stores
    description: Vector store creation and query endpoints
  - name: Videos
    description: Video generation and remixing using Sora 2 Pro
paths:
  /v1/responses:
    post:
      tags:
        - Responses
      summary: Create a model response
      operationId: createResponse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResponseCreate'
      responses:
        '200':
          description: Model response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseObject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/responses/{response_id}:
    get:
      tags:
        - Responses
      summary: Retrieve a response
      operationId: getResponse
      parameters:
        - name: response_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Response object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseObject'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/responses/{response_id}/cancel:
    post:
      tags:
        - Responses
      summary: Cancel a running response
      operationId: cancelResponse
      parameters:
        - name: response_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cancelled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AckObject'
        '400':
          description: Invalid ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/models:
    get:
      tags:
        - Models
      summary: List models
      operationId: listModels
      responses:
        '200':
          description: Model list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericObject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/files:
    get:
      tags:
        - Files
      summary: List files
      operationId: listFiles
      responses:
        '200':
          description: Files
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericObject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
    post:
      tags:
        - Files
      summary: Upload file
      operationId: createFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              additionalProperties: false
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileObject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/files/{file_id}:
    get:
      tags:
        - Files
      summary: Get file metadata
      operationId: getFile
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileObject'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/files/{file_id}/content:
    get:
      tags:
        - Files
      summary: Download file content
      operationId: getFileContent
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Raw file bytes
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/uploads:
    post:
      tags:
        - Uploads
      summary: Create upload session
      operationId: createUpload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenericObject'
      responses:
        '200':
          description: Upload created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadObject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/uploads/{upload_id}/parts:
    post:
      tags:
        - Uploads
      summary: Upload a part
      operationId: uploadPart
      parameters:
        - name: upload_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Part accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AckObject'
        '404':
          description: Upload not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/uploads/{upload_id}/complete:
    post:
      tags:
        - Uploads
      summary: Complete upload
      operationId: completeUpload
      parameters:
        - name: upload_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadObject'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/images/generations:
    post:
      tags:
        - Images
      summary: Generate image
      operationId: createImageGeneration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenericObject'
      responses:
        '200':
          description: Image result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericObject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/images/edits:
    post:
      tags:
        - Images
      summary: Edit image
      operationId: createImageEdit
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
              additionalProperties: true
      responses:
        '200':
          description: Image edit result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericObject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/audio/transcriptions:
    post:
      tags:
        - Audio
      summary: Transcribe audio
      operationId: createTranscription
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              additionalProperties: true
      responses:
        '200':
          description: Transcription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericObject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/audio/translations:
    post:
      tags:
        - Audio
      summary: Translate audio
      operationId: createTranslation
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              additionalProperties: true
      responses:
        '200':
          description: Translation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericObject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/audio/speech:
    post:
      tags:
        - Audio
      summary: Text to speech
      operationId: createSpeech
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenericObject'
      responses:
        '200':
          description: Audio stream
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/vector_stores:
    get:
      tags:
        - Vector Stores
      summary: List vector stores
      operationId: listVectorStores
      responses:
        '200':
          description: Vector store list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericObject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
    post:
      tags:
        - Vector Stores
      summary: Create vector store
      operationId: createVectorStore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenericObject'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VectorStoreObject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/videos:
    post:
      tags:
        - Videos
      summary: Create a video generation job (Sora 2 Pro)
      operationId: createVideo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoCreate'
      responses:
        '200':
          description: Video job created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoObject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/videos/{video_id}:
    get:
      tags:
        - Videos
      summary: Retrieve a video job
      operationId: getVideo
      parameters:
        - name: video_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Video metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoObject'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/videos/{video_id}/content:
    get:
      tags:
        - Videos
      summary: Download or stream generated video (MP4)
      operationId: getVideoContent
      parameters:
        - name: video_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Video stream
          content:
            video/mp4:
              schema:
                type: string
                format: binary
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /v1/videos/{video_id}/remix:
    post:
      tags:
        - Videos
      summary: Remix an existing video using Sora 2 Pro
      operationId: remixVideo
      parameters:
        - name: video_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoRemix'
      responses:
        '200':
          description: Remix job created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoObject'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    ErrorObject:
      type: object
      properties:
        error:
          type: object
          properties:
            type:
              type: string
            message:
              type: string
          required:
            - type
            - message
      required:
        - error
      additionalProperties: false
    AckObject:
      type: object
      properties:
        ok:
          type: boolean
          default: true
      required:
        - ok
      additionalProperties: false
    GenericObject:
      type: object
      properties:
        note:
          type: string
      additionalProperties: true
    ResponseCreate:
      type: object
      properties: {}
      additionalProperties: true
    ResponseObject:
      type: object
      properties: {}
      additionalProperties: true
    FileObject:
      type: object
      properties: {}
      additionalProperties: true
    UploadObject:
      type: object
      properties: {}
      additionalProperties: true
    VectorStoreObject:
      type: object
      properties: {}
      additionalProperties: true
    VideoCreate:
      type: object
      properties:
        model:
          type: string
          default: sora-2-pro
        prompt:
          type: string
        input_reference:
          type: string
          description: Optional image or file ID reference
        seconds:
          type: integer
          default: 10
      required:
        - model
        - prompt
      additionalProperties: false
    VideoRemix:
      type: object
      properties:
        prompt:
          type: string
        parameters:
          type: object
          additionalProperties: true
      required:
        - prompt
      additionalProperties: true
    VideoObject:
      type: object
      properties:
        id:
          type: string
        object:
          type: string
          default: video
        model:
          type: string
        status:
          type: string
          enum:
            - queued
            - processing
            - completed
            - failed
        seconds:
          type: integer
        size:
          type: string
        progress:
          type: number
        remixed_from_video_id:
          type:
            - string
            - 'null'
        created_at:
          type: integer
        purpose:
          type: string
      required:
        - id
        - object
        - model
        - status
      additionalProperties: true
