/* tslint:disable */
/* eslint-disable */
/**
 * ChatGPT Relay Full Schema (SDK-aligned)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AssistantRequest
 */
export interface AssistantRequest {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof AssistantRequest
     */
    'model': string;
    /**
     * 
     * @type {Array<ChatMessage>}
     * @memberof AssistantRequest
     */
    'input': Array<ChatMessage>;
}
/**
 * 
 * @export
 * @interface ChatCompletionRequest
 */
export interface ChatCompletionRequest {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof ChatCompletionRequest
     */
    'model': string;
    /**
     * 
     * @type {Array<ChatMessage>}
     * @memberof ChatCompletionRequest
     */
    'messages': Array<ChatMessage>;
    /**
     * 
     * @type {Array<ToolDefinition>}
     * @memberof ChatCompletionRequest
     */
    'tools'?: Array<ToolDefinition>;
    /**
     * 
     * @type {ChatCompletionRequestToolChoice}
     * @memberof ChatCompletionRequest
     */
    'tool_choice'?: ChatCompletionRequestToolChoice;
}
/**
 * @type ChatCompletionRequestToolChoice
 * @export
 */
export type ChatCompletionRequestToolChoice = ChatCompletionRequestToolChoiceOneOf | string;

/**
 * 
 * @export
 * @interface ChatCompletionRequestToolChoiceOneOf
 */
export interface ChatCompletionRequestToolChoiceOneOf {
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionRequestToolChoiceOneOf
     */
    'type'?: string;
    /**
     * 
     * @type {FunctionCall}
     * @memberof ChatCompletionRequestToolChoiceOneOf
     */
    'function'?: FunctionCall;
}
/**
 * 
 * @export
 * @interface ChatCompletionResponse
 */
export interface ChatCompletionResponse {
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    'object'?: string;
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionResponse
     */
    'created'?: number;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    'model'?: string;
    /**
     * 
     * @type {Array<ChatCompletionResponseChoicesInner>}
     * @memberof ChatCompletionResponse
     */
    'choices'?: Array<ChatCompletionResponseChoicesInner>;
}
/**
 * 
 * @export
 * @interface ChatCompletionResponseChoicesInner
 */
export interface ChatCompletionResponseChoicesInner {
    /**
     * 
     * @type {ChatMessage}
     * @memberof ChatCompletionResponseChoicesInner
     */
    'message'?: ChatMessage;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponseChoicesInner
     */
    'finish_reason'?: string;
}
/**
 * 
 * @export
 * @interface ChatMessage
 */
export interface ChatMessage {
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    'role': ChatMessageRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    'content': string;
    /**
     * 
     * @type {Array<ToolCall>}
     * @memberof ChatMessage
     */
    'tool_calls'?: Array<ToolCall>;
}

export const ChatMessageRoleEnum = {
    System: 'system',
    User: 'user',
    Assistant: 'assistant',
    Tool: 'tool'
} as const;

export type ChatMessageRoleEnum = typeof ChatMessageRoleEnum[keyof typeof ChatMessageRoleEnum];

/**
 * 
 * @export
 * @interface FunctionCall
 */
export interface FunctionCall {
    /**
     * 
     * @type {string}
     * @memberof FunctionCall
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof FunctionCall
     */
    'arguments': string;
}
/**
 * 
 * @export
 * @interface ToolCall
 */
export interface ToolCall {
    /**
     * Unique ID
     * @type {string}
     * @memberof ToolCall
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ToolCall
     */
    'type'?: ToolCallTypeEnum;
    /**
     * 
     * @type {FunctionCall}
     * @memberof ToolCall
     */
    'function'?: FunctionCall;
}

export const ToolCallTypeEnum = {
    Function: 'function'
} as const;

export type ToolCallTypeEnum = typeof ToolCallTypeEnum[keyof typeof ToolCallTypeEnum];

/**
 * 
 * @export
 * @interface ToolDefinition
 */
export interface ToolDefinition {
    /**
     * 
     * @type {string}
     * @memberof ToolDefinition
     */
    'type': ToolDefinitionTypeEnum;
    /**
     * 
     * @type {ToolDefinitionFunction}
     * @memberof ToolDefinition
     */
    'function': ToolDefinitionFunction;
}

export const ToolDefinitionTypeEnum = {
    Function: 'function'
} as const;

export type ToolDefinitionTypeEnum = typeof ToolDefinitionTypeEnum[keyof typeof ToolDefinitionTypeEnum];

/**
 * 
 * @export
 * @interface ToolDefinitionFunction
 */
export interface ToolDefinitionFunction {
    /**
     * 
     * @type {string}
     * @memberof ToolDefinitionFunction
     */
    'name': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ToolDefinitionFunction
     */
    'parameters': { [key: string]: any; };
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Fetch assistant details
         * @param {string} assistantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1AssistantsAssistantIdGet: async (assistantId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'assistantId' is not null or undefined
            assertParamExists('v1AssistantsAssistantIdGet', 'assistantId', assistantId)
            const localVarPath = `/v1/assistants/{assistant_id}`
                .replace(`{${"assistant_id"}}`, encodeURIComponent(String(assistantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create assistant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1AssistantsPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/assistants`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Modern Chat Completion with tool calling
         * @param {ChatCompletionRequest} chatCompletionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ChatCompletionsPost: async (chatCompletionRequest: ChatCompletionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatCompletionRequest' is not null or undefined
            assertParamExists('v1ChatCompletionsPost', 'chatCompletionRequest', chatCompletionRequest)
            const localVarPath = `/v1/chat/completions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(chatCompletionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List available models
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ModelsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/models`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Streamable response via SSE
         * @param {AssistantRequest} assistantRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ResponsesPost: async (assistantRequest: AssistantRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'assistantRequest' is not null or undefined
            assertParamExists('v1ResponsesPost', 'assistantRequest', assistantRequest)
            const localVarPath = `/v1/responses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(assistantRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Start thread
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ThreadsPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/threads`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Add user message to thread
         * @param {string} threadId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ThreadsThreadIdMessagesPost: async (threadId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'threadId' is not null or undefined
            assertParamExists('v1ThreadsThreadIdMessagesPost', 'threadId', threadId)
            const localVarPath = `/v1/threads/{thread_id}/messages`
                .replace(`{${"thread_id"}}`, encodeURIComponent(String(threadId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Start a tool-calling run
         * @param {string} threadId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ThreadsThreadIdRunsPost: async (threadId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'threadId' is not null or undefined
            assertParamExists('v1ThreadsThreadIdRunsPost', 'threadId', threadId)
            const localVarPath = `/v1/threads/{thread_id}/runs`
                .replace(`{${"thread_id"}}`, encodeURIComponent(String(threadId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Fetch execution steps
         * @param {string} threadId 
         * @param {string} runId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ThreadsThreadIdRunsRunIdStepsGet: async (threadId: string, runId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'threadId' is not null or undefined
            assertParamExists('v1ThreadsThreadIdRunsRunIdStepsGet', 'threadId', threadId)
            // verify required parameter 'runId' is not null or undefined
            assertParamExists('v1ThreadsThreadIdRunsRunIdStepsGet', 'runId', runId)
            const localVarPath = `/v1/threads/{thread_id}/runs/{run_id}/steps`
                .replace(`{${"thread_id"}}`, encodeURIComponent(String(threadId)))
                .replace(`{${"run_id"}}`, encodeURIComponent(String(runId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Fetch assistant details
         * @param {string} assistantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1AssistantsAssistantIdGet(assistantId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1AssistantsAssistantIdGet(assistantId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.v1AssistantsAssistantIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create assistant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1AssistantsPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1AssistantsPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.v1AssistantsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Modern Chat Completion with tool calling
         * @param {ChatCompletionRequest} chatCompletionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ChatCompletionsPost(chatCompletionRequest: ChatCompletionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChatCompletionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ChatCompletionsPost(chatCompletionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.v1ChatCompletionsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List available models
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ModelsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ModelsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.v1ModelsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Streamable response via SSE
         * @param {AssistantRequest} assistantRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ResponsesPost(assistantRequest: AssistantRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ResponsesPost(assistantRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.v1ResponsesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Start thread
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ThreadsPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ThreadsPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.v1ThreadsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Add user message to thread
         * @param {string} threadId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ThreadsThreadIdMessagesPost(threadId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ThreadsThreadIdMessagesPost(threadId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.v1ThreadsThreadIdMessagesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Start a tool-calling run
         * @param {string} threadId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ThreadsThreadIdRunsPost(threadId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ThreadsThreadIdRunsPost(threadId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.v1ThreadsThreadIdRunsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Fetch execution steps
         * @param {string} threadId 
         * @param {string} runId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ThreadsThreadIdRunsRunIdStepsGet(threadId: string, runId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ThreadsThreadIdRunsRunIdStepsGet(threadId, runId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.v1ThreadsThreadIdRunsRunIdStepsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Fetch assistant details
         * @param {string} assistantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1AssistantsAssistantIdGet(assistantId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1AssistantsAssistantIdGet(assistantId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create assistant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1AssistantsPost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1AssistantsPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Modern Chat Completion with tool calling
         * @param {ChatCompletionRequest} chatCompletionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ChatCompletionsPost(chatCompletionRequest: ChatCompletionRequest, options?: RawAxiosRequestConfig): AxiosPromise<ChatCompletionResponse> {
            return localVarFp.v1ChatCompletionsPost(chatCompletionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List available models
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ModelsGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1ModelsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Streamable response via SSE
         * @param {AssistantRequest} assistantRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ResponsesPost(assistantRequest: AssistantRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1ResponsesPost(assistantRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Start thread
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ThreadsPost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1ThreadsPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Add user message to thread
         * @param {string} threadId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ThreadsThreadIdMessagesPost(threadId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1ThreadsThreadIdMessagesPost(threadId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Start a tool-calling run
         * @param {string} threadId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ThreadsThreadIdRunsPost(threadId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1ThreadsThreadIdRunsPost(threadId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Fetch execution steps
         * @param {string} threadId 
         * @param {string} runId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ThreadsThreadIdRunsRunIdStepsGet(threadId: string, runId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1ThreadsThreadIdRunsRunIdStepsGet(threadId, runId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Fetch assistant details
     * @param {string} assistantId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public v1AssistantsAssistantIdGet(assistantId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).v1AssistantsAssistantIdGet(assistantId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create assistant
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public v1AssistantsPost(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).v1AssistantsPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Modern Chat Completion with tool calling
     * @param {ChatCompletionRequest} chatCompletionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public v1ChatCompletionsPost(chatCompletionRequest: ChatCompletionRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).v1ChatCompletionsPost(chatCompletionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List available models
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public v1ModelsGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).v1ModelsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Streamable response via SSE
     * @param {AssistantRequest} assistantRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public v1ResponsesPost(assistantRequest: AssistantRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).v1ResponsesPost(assistantRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Start thread
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public v1ThreadsPost(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).v1ThreadsPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Add user message to thread
     * @param {string} threadId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public v1ThreadsThreadIdMessagesPost(threadId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).v1ThreadsThreadIdMessagesPost(threadId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Start a tool-calling run
     * @param {string} threadId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public v1ThreadsThreadIdRunsPost(threadId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).v1ThreadsThreadIdRunsPost(threadId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Fetch execution steps
     * @param {string} threadId 
     * @param {string} runId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public v1ThreadsThreadIdRunsRunIdStepsGet(threadId: string, runId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).v1ThreadsThreadIdRunsRunIdStepsGet(threadId, runId, options).then((request) => request(this.axios, this.basePath));
    }
}



