# ==========================================================
# app/routes/openapi.py — Relay OpenAPI Specification Route
# ==========================================================
# Exposes the full OpenAPI 3.1 schema generated by FastAPI.
# Used for introspection, SDK generation, and relay verification.
# Mirrors the OpenAI API surface for plugin discovery and tooling.
# ==========================================================

import yaml
from fastapi import APIRouter, Request, Response
from fastapi.openapi.utils import get_openapi

router = APIRouter(prefix="/v1", tags=["OpenAPI"])

@router.get("/openapi.yaml", summary="Retrieve OpenAPI YAML schema")
async def get_openapi_yaml(request: Request):
    """
    Generate and return the OpenAPI 3.1 schema for this relay in YAML format.
    This endpoint allows clients (like ChatGPT or SDK generators) to discover
    the full API structure dynamically — including /v1/responses, /v1/realtime,
    /v1/tools, and any local relay extensions.
    """
    schema = get_openapi(
        title="ChatGPT Team Relay API",
        version="2025-10",
        description=(
            "OpenAI-compatible API specification for the ChatGPT Team Relay.\n"
            "This OpenAPI 3.1 schema mirrors the official OpenAI API endpoints "
            "and supports introspection, SDK generation, and plugin registration."
        ),
        routes=request.app.routes,
    )

    # Inject metadata used by plugin and discovery clients
    schema["info"]["x-relay-version"] = "v2.3.4-fp"
    schema["info"]["x-ground-truth"] = "OpenAI API Reference 2025-10"
    schema["info"]["contact"] = {
        "name": "ChatGPT Team Relay Maintainers",
        "email": "support@yourdomain.com",
        "url": "https://yourdomain.com"
    }
    schema["externalDocs"] = {
        "description": "Official OpenAI API Reference",
        "url": "https://api.openai.com/docs"
    }

    # Convert to YAML format
    yaml_schema = yaml.safe_dump(schema, sort_keys=False, allow_unicode=True)
    return Response(content=yaml_schema, media_type="application/x-yaml")

@router.get("/openapi.json", summary="Retrieve OpenAPI JSON schema")
async def get_openapi_json(request: Request):
    """
    Alternate version returning JSON instead of YAML.
    Some clients (like SDK generators) prefer JSON for schema imports.
    """
    schema = get_openapi(
        title="ChatGPT Team Relay API",
        version="2025-10",
        description="OpenAI-compatible relay API schema (ChatGPT Team Relay).",
        routes=request.app.routes,
    )
    return Response(content=yaml.safe_dump(schema, sort_keys=False), media_type="application/json")
